version: "3.8"

services:
  ui:
    build:
      context: ./client
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - ./client:/app/
      - /app/node_modules
    ports:
      - 3000:3000
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - ./server:/app/
      - /app/node_modules
    ports:
      - 8000:8000
    environment:
      - DB_DEPLOYMENT_TYPE=remote
      - DB_TYPE=yugabytedb
      - DB_HOST=[YUGABYTEDB_HOST]
      - DB_PASSWORD=[YUGABYTEDB_MANAGED_PASSWORD]
      - DB_NAME=yugabyte
      - DB_USER=admin
      - DB_SSL_MODE=true
